-- Mailer queries

INSERT INTO prospects.mailer_queries VALUES ('linc_prospects_email', 'info@cookwithlinc.com', 'SELECT id, lead_id, lead_source, app_name, email, phone_number, miscellaneous, was_processed, is_valid FROM prospects.sneezers WHERE lead_source IN (''email'', ''landing'') AND email IS NOT NULL AND replied_to = FALSE ORDER BY id ASC LIMIT $1', 'email', 'Thank you for your interest in Linc!', NULL, 'http://hayden.hopto.org/~hjames/prospects/example/email.html', 'UPDATE prospects.leads SET replied_to = TRUE, updated_at = $1 WHERE id = $2', 'id', current_timestamp, current_timestamp);

INSERT INTO prospects.mailer_queries VALUES ('linc_funders_pledged_email', 'info@cookwithlinc.com', 'SELECT id, perk_name, campaign_name, amount, currency, contact_email FROM funders.active_pledges WHERE replied_to = FALSE ORDER BY created_at ASC LIMIT $1', 'contact_email', 'Thank you for your pledging to buy Linc perk %s!', ARRAY['perk_name'], 'http://hayden.hopto.org/~hjames/prospects/example/email.html', 'UPDATE funders.pledges SET replied_to = TRUE, updated_at = $1 WHERE id = $2', 'id', current_timestamp, current_timestamp);

INSERT INTO prospects.mailer_queries VALUES ('linc_funders_purchased_email', 'info@cookwithlinc.com', 'SELECT id, perk_name, campaign_name, amount, currency, contact_email FROM funders.active_payments WHERE replied_to = FALSE ORDER BY created_at ASC LIMIT $1', 'contact_email', 'Thank you for your purchasing Linc perk %s!', ARRAY['perk_name'], 'http://hayden.hopto.org/~hjames/prospects/example/email.html', 'UPDATE funders.pledges SET replied_to = TRUE, updated_at = $1 WHERE id = $2', 'id', current_timestamp, current_timestamp);

INSERT INTO prospects.mailer_queries VALUES ('linc_funders_fullfillment_email', 'info@cookwithlinc.com', 'SELECT id, perk_name, campaign_name, amount, currency, contact_email FROM funders.active_pledges WHERE replied_to = FALSE ORDER BY created_at ASC LIMIT $1', 'contact_email', 'Please pay for Linc perk %s', ARRAY['perk_name'], 'http://hayden.hopto.org/~hjames/prospects/example/email.html', 'UPDATE funders.pledges SET requested_payment = requested_payment + 1, updated_at = $1 WHERE id = $2', 'id', current_timestamp, current_timestamp);
